server:
  port: 8084

spring:
  application:
    name : MyService
   
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      javax:
        persistence:
          query:
            timeout:4000
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          
      show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampleschema?connectTimeout=150&socketTimeout=150
    username: root
    password: 1234
    tomcat:
      max-Active: 20
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        threadpool:
          myThreadPool:
            coreSize: 2
            maximumSize: 20 
            allowMaximumSizeToDivergeFromCoreSize : true
        isolation:
          thread:
            timeoutInMilliseconds: 19000
            
    updateCreditInfo:
      execution:
        timeout:
          enabled: true
          
    updateCreditInfoAlt:
      execution:
        timeout:
          enabled: true
    getValue:
      execution:
        timeout:
          enabled: true
   
            